apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: k8s-pet
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/app/images"
              name: images
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: webservice