apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: local
